version: '3'

services:
  mysqlsrv:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "Chico@1234"
      MYSQL_DATABASE: "dbAPI"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql/data      
    # volumes:
    #   - /home/chicofronza/Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
